### ISSUE TITLE
NodeJS Server Endpoints Returning 404 for OAS3 Specs

### ISSUE THREAD

**Issue by mestrega** [bug-hunters/oas3-tools#1]
When using Swagger Editor to build the NodeJS Server from a YAML structure, the Swagger UI and localhost:3000/api-docs works, no other endpoints are working, including the root. All of these return 404 errors:
localhost:3000/
localhost:3000/user?name=value
localhost:3000/api/v1/user?name=value

My YAML Servers look like this:
servers:
  - url: http://localhost:3000/api/v1
    description: REST API Localhost
  - url: https://stg.example.com:3000/api/v1
    description: REST API Staging
  - url: https://prd.example.com:3000/api/v1
    description: REST API Production

The "/api/v1/user" endpoint is configured like this:
  /user:
    get:
      tags:
      - user
      summary: Get user by Username, E-Mail, or ID.
      description: Get User data by the Users Unique Username, E-Mail, or ID. /user?user={ username | email | id }
      operationId: getUser
      parameters:
      - name: user
        in: query
        description: The user that needs to be fectched.
        required: true
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
            application/xml:
              schema:
                $ref: '#/components/schemas/User'
            text/plain:
              schema:
                $ref: '#/components/schemas/User'
        400:
          description: Invalid username supplied
          content:
            application/json:
              schema:
                type: string
            application/xml:
              schema:
                type: string
            text/plain:
              schema:
                type: string
        404:
          description: User not found
          content:
            application/json:
              schema:
                type: string
            application/xml:
              schema:
                type: string
            text/plain:
              schema:
                type: string
        default:
          description: OK
          content:
            application/json:
              schema:
                type: string
            application/xml:
              schema:
                type: string
            text/plain:
              schema:
                type: string
      x-swagger-router-controller: user

**Comment by mestrega** [comment]
It looks like the `initializeMiddleware` method isn't using the provided `callback` function.

```JAVASCRIPT
// index.js
// Provides Output of swaggerDoc
console.log(swaggerDoc);
oas3Tools.initializeMiddleware(swaggerDoc,function(middleware){
  // Does not output anything
  console.log(middleware);
  console.log('test');
});
```

I also get output all the way to the end of the `initializeMiddleware` function in `node_modules/oas3-tools/index.js`:

```JAVASCRIPT
// node_modules/oas3-tools/index.js

...
  console.log(args);
// Outputs
/*
 [ { openapi: '3.0.0',
    info:
     { title: 'REST API',
       description:
        'Site Description',
       termsOfService: 'https://www.example.com/',
       contact: [Object],
       version: '1.0.0' },
    servers: [ [Object], [Object], [Object] ],
    tags: [ [Object], [Object], [Object], [Object] ],
    paths:
     { '/admin/user': [Object],
       '/admin/users': [Object],
       '/user': [Object],
       '/user/login': [Object],
       '/user/logout': [Object],
       '/users': [Object],
       '/users/find': [Object] },
    components: { schemas: [Object] } },
  [Function] ]
*/
// args[1] outputs "[Function]", which I assume is the `callback` function
  spec.validate.apply(spec, args);
  console.log('');
  console.log(spec);
// Outputs
/*
Specification {
  docsUrl:
   'https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md',
  primitives:
   [ 'string', 'number', 'boolean', 'integer', 'array', 'file' ],
  schemasUrl: '¯_(ツ)_/¯',
  schemas:
   { 'schema.json':
      { id: '',
        '$schema': 'http://json-schema.org/draft-04/schema#',
        type: 'object',
        required: [Array],
        properties: [Object],
        patternProperties: [Object],
        additionalProperties: false,
        definitions: [Object] } },
  version: '3.0.0' }
*/
};

console.log(initializeMiddleware);
// Outputs
// [Function: initializeMiddleware]

module.exports = {
  initializeMiddleware: initializeMiddleware,
  specs: require('./lib/specs')
};
```

Other than this, I'm unable to get any other error or failure messages to log or output, but the call back for `initializeMiddleware` isn't getting called in `/index.js`.

**Comment by mestrega** [comment]
Thanks @HugoMario , Please let me know through PM if there is anything I can do to lend a hand when you get around it. Happy to help in anyway that I can.

**Comment by mestrega** [comment]
After further exploration, I've narrowed it down to
```
./index.js
// Interpret Swagger resources and attach metadata to request - must be first in swagger-tools middleware chain
app.use(metadata.swaggerMetadata(swaggerDoc));
```

Which then returns the Error:
```
3|build3  | Error initializing middleware
3|build3  | Error: rlOrSO is required
3|build3  |     at processSwaggerDocuments (\node_modules\oas3-tools\middleware\swagger-metadata.js:230:11)
3|build3  |     at Object.module.exports (\node_modules\oas3-tools\middleware\swagger-metadata.js:376:18)
3|build3  |     at Object.swaggerMetadata (\node_modules\oas3-tools\index.js:165:34)
3|build3  |     at \index.js:50:22
3|build3  |     at test (\node_modules\oas3-tools\index.js:159:7)
3|build3  |     at Object.initializeMiddleware (\node_modules\oas3-tools\index.js:207:13)
3|build3  |     at Object.<anonymous> (\index.js:47:11)
3|build3  |     at Module._compile (internal/modules/cjs/loader.js:702:30)
3|build3  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
3|build3  |     at Module.load (internal/modules/cjs/loader.js:612:32)
```
In order to get this feed back, I had to pull the function out of `args.push()` in `\node_modules\oas3-tools\index.js`, declare it seperatly and then call it from the `args.push()`.

```
var out = function (err, results) {
   /*All of the contents of the function remained the same*/
}
args.push(out());
```

However, in `\node_moduls\oas3-tools\index.js` when `swagger-middleware` is called, it is passing an `undefined` parameter and an empty array `[]`.

Even replacing `args.slice(0, args.length - 1)` with `rlOrSO` and `args[0]` returns the same error as above.

`args[0]` logs the passed in Swagger Object.

**Comment by mestrega** [comment]
There is also an issue related to this in `/node_modules/oas3-tools/middleware/swagger-router.js`

In the `return function swaggerRouter()` definition, `req.swagger` does not exist, so that the following ALWAYS returns "NO":

`debug('  Will process: %s', _.isUndefined(operation) ? 'no' : 'yes');` WHERE
`var operation = req.swagger ? req.swagger.operation : undefined;` becuase req.swagger does not exist and is therefore set to `undefined`.

**Comment by HugoMario** [comment]
hello @mestrega, sorry for this response delay. i could take a time now to review this issue. when you have a chance, can you please share the `YAML` file you're using? i've been testing this, but i can reach other endpoints.

**Comment by mestrega** [comment]
No worries. I understand getting busy. Had to clean the file.

[openapi-sharable.zip](https://github.com/bug-hunters/oas3-tools/files/2852755/openapi-sharable.zip)

**Comment by mestrega** [comment]
Is there any additional information I can provide you with to help out?

**Comment by HugoMario** [comment]
hey @mestrega no really, sorry for delay, going to try this now and let you know

**Comment by HugoMario** [comment]
@mestrega i just checked and saw some improvement to apply, but before continue i would like to know if you have a solution in mind and willing to create PR. it's ok if you're not, just trying to avoid doubble work for this.

**Comment by HugoMario** [comment]
@mestrega, just found the real reason of this issue, the module is not working properly with `3.0.0` versions but it is with `3.0.1`, i'll add a fix and create a new release for it.

**Comment by mestrega** [comment]
I do not have a solution in mind. Plus, I'm not sure how comfortable I would be with making changes to Core Code, as I'm not an "expert" in JS. I will take a look at my YAML file and adjust it to 3.0.1 to see if that resolves the issue. If there is something specific you'd like me to do on the project, please let me know and I will make those changes and submit a PR.

**Comment by mestrega** [comment]
As a follow-up, I can confirm that switching "openapi: 3.0.0" to "openapi: 3.0.1" resolved the issue. Thanks you very much for pointing this out, It never dawned on me that this could be the issue.

**Comment by mestrega** [comment]
It also doesn't look like it's exporting the Authorization parts either. In the Editor, I can see the Authorize button and symbols on the endpoint headers, but once compiled, "Authorize" is not visible.

**Comment by mestrega** [comment]
As a second note, I would like to take an active part in getting these issues resolved, I'll just need some guidance through the code at first maybe. How could I go about getting you my contact info?
