### ISSUE TITLE
update with v2.2.0 breaks semver rules

### ISSUE THREAD

**Issue by marc22alain** [bug-hunters/oas3-tools#30]
Removal of the `addValidator` function is a major, non-backwards-compatible, change to the API. 
According to the rules of [semantic versioning](https://semver.org/), this kind of change requires a **major** version update.

So I discovered this a few days ago when I attempted to auto-generate a NodeJS server from a swagger definition. 
This is what I found:
```
/Users/marc.deniverville/Downloads/nodejs-server-server-generated/index.js:15
expressAppConfig.addValidator();
                 ^

TypeError: expressAppConfig.addValidator is not a function
    at Object.<anonymous> (/Users/marc.deniverville/Downloads/nodejs-server-server-generated/index.js:15:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

The auto-generated **package.json** file makes this reference to **oas3-tools**: `"oas3-tools": "^2.0.2"`, accepting patch and minor point upgrades.

**Comment by gaboAcosta** [comment]
Agreed, please remove version 2.2.0 and bump to 3.0.1 so that you don't break clients allowing minor version updates, thanks!

**Comment by gaboAcosta** [comment]
We were using 2.0.2, tried 2.1.3 and is broken too, it looks like there have been some backwards compatibility issues on the releases, I will try to figure out the right version where it broke but on the meantime, we are freezing any updates from 2.0.2

**Comment by fwermus** [comment]
Any solution to this?
